"""null referenced tweets and cascade delete referenced media

Revision ID: 2c84b4280fd8
Revises: 5d172a7655be
Create Date: 2022-11-19 14:03:34.411152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c84b4280fd8'
down_revision = '5d172a7655be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('media_ibfk_1', 'media', type_='foreignkey')
    op.create_foreign_key(None, 'media', 'tweet', ['tweet_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('tweet_ibfk_4', 'tweet', type_='foreignkey')
    op.drop_constraint('tweet_ibfk_3', 'tweet', type_='foreignkey')
    op.drop_constraint('tweet_ibfk_2', 'tweet', type_='foreignkey')
    op.drop_constraint('tweet_ibfk_1', 'tweet', type_='foreignkey')
    op.create_foreign_key(None, 'tweet', 'tweet', ['replied_tweet_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tweet', 'tweet', ['quoted_tweet_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tweet', 'tweet', ['_conversation_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tweet', 'tweet', ['retweeted_tweet_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('video_version_ibfk_1', 'video_version', type_='foreignkey')
    op.create_foreign_key(None, 'video_version', 'media', ['video_key'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video_version', type_='foreignkey')
    op.create_foreign_key('video_version_ibfk_1', 'video_version', 'media', ['video_key'], ['id'])
    op.drop_constraint(None, 'tweet', type_='foreignkey')
    op.drop_constraint(None, 'tweet', type_='foreignkey')
    op.drop_constraint(None, 'tweet', type_='foreignkey')
    op.drop_constraint(None, 'tweet', type_='foreignkey')
    op.create_foreign_key('tweet_ibfk_1', 'tweet', 'tweet', ['_conversation_id'], ['id'])
    op.create_foreign_key('tweet_ibfk_2', 'tweet', 'tweet', ['quoted_tweet_id'], ['id'])
    op.create_foreign_key('tweet_ibfk_3', 'tweet', 'tweet', ['replied_tweet_id'], ['id'])
    op.create_foreign_key('tweet_ibfk_4', 'tweet', 'tweet', ['retweeted_tweet_id'], ['id'])
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.create_foreign_key('media_ibfk_1', 'media', 'tweet', ['tweet_id'], ['id'])
    # ### end Alembic commands ###
