"""Track when queued tweet was added

Revision ID: 5a074b3498ff
Revises: e406f5e74751
Create Date: 2023-02-07 02:27:18.466798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a074b3498ff'
down_revision = 'e406f5e74751'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queued_tweet', sa.Column('added', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_queued_tweet_added'), 'queued_tweet', ['added'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_queued_tweet_added'), table_name='queued_tweet')
    op.drop_column('queued_tweet', 'added')
    # ### end Alembic commands ###
