"""InitialCreate

Revision ID: 5d172a7655be
Revises: 
Create Date: 2022-11-18 18:02:01.153087

"""
from alembic import op
import sqlalchemy as sa

from model.types.int_list import IntList


# revision identifiers, used by Alembic.
revision = '5d172a7655be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweet',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('text', sa.String(length=512), nullable=False),
    sa.Column('edit_history_tweet_ids', IntList(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entities', sa.String(length=4096), nullable=False),
    sa.Column('retweet_count', sa.Integer(), nullable=False),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('quote_count', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('_conversation_id', sa.BigInteger(), nullable=True),
    sa.Column('replied_tweet_id', sa.BigInteger(), nullable=True),
    sa.Column('quoted_tweet_id', sa.BigInteger(), nullable=True),
    sa.Column('retweeted_tweet_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['_conversation_id'], ['tweet.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], use_alter=True),
    sa.ForeignKeyConstraint(['quoted_tweet_id'], ['tweet.id'], ),
    sa.ForeignKeyConstraint(['replied_tweet_id'], ['tweet.id'], ),
    sa.ForeignKeyConstraint(['retweeted_tweet_id'], ['tweet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media',
    sa.Column('id', sa.String(length=32), autoincrement=False, nullable=False),
    sa.Column('type', sa.Enum('ANIMATED_GIF', 'PHOTO', 'VIDEO', name='emediatype'), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('alt_text', sa.String(length=1024), nullable=True),
    sa.Column('tweet_id', sa.BigInteger(), nullable=True),
    sa.Column('downloaded', sa.Boolean(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('entities', sa.String(length=4096), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('profile_image_url', sa.String(length=1024), nullable=False),
    sa.Column('profile_image_downloaded', sa.Boolean(), nullable=False),
    sa.Column('profile_image_file_path', sa.String(length=512), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=False),
    sa.Column('following_count', sa.Integer(), nullable=False),
    sa.Column('tweet_count', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('pinned_tweet_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['pinned_tweet_id'], ['tweet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_version',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('bit_rate', sa.Integer(), nullable=True),
    sa.Column('video_key', sa.String(length=32), nullable=False),
    sa.Column('downloaded', sa.Boolean(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['video_key'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key('tweet_author_FK', 'tweet', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_version')
    op.drop_table('user')
    op.drop_table('media')
    op.drop_table('tweet')
    # ### end Alembic commands ###
