"""Increase Tweet text length

Revision ID: 6755532981c7
Revises: 5a074b3498ff
Create Date: 2023-03-12 14:38:03.149518

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6755532981c7'
down_revision = '5a074b3498ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tweet', 'text',
               existing_type=mysql.VARCHAR(length=512),
               type_=sa.String(length=8192),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tweet', 'text',
               existing_type=sa.String(length=8192),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=False)
    # ### end Alembic commands ###
