"""conversation_id rename

Revision ID: 74516bcc41bf
Revises: 2c84b4280fd8
Create Date: 2022-11-19 14:17:27.189930

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '74516bcc41bf'
down_revision = '2c84b4280fd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tweet_ibfk_3', 'tweet', type_='foreignkey')
    op.alter_column('tweet', '_conversation_id', new_column_name='conversation_id', existing_type=sa.BigInteger, existing_nullable=True, existing_server_default=None)
    op.create_foreign_key('tweet_ibfk_3', 'tweet', 'tweet', ['conversation_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tweet_ibfk_3', 'tweet', type_='foreignkey')
    op.alter_column('tweet', 'conversation_id', new_column_name='_conversation_id', existing_type=sa.BigInteger, existing_nullable=True, existing_server_default=None)
    op.create_foreign_key('tweet_ibfk_3', 'tweet', 'tweet', ['_conversation_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
