"""longer entities

Revision ID: e8487242e5bb
Revises: 305afd97eb18
Create Date: 2023-02-05 11:14:08.440909

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8487242e5bb'
down_revision = '305afd97eb18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tweet', 'entities',
               existing_type=mysql.VARCHAR(length=4096),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tweet', 'entities',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=4096),
               existing_nullable=False)
    # ### end Alembic commands ###
